"""empty message

Revision ID: 3bcfa0fc74f8
Revises: 13aa8c6fd31c
Create Date: 2021-05-06 15:01:14.667742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bcfa0fc74f8'
down_revision = '13aa8c6fd31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_comments',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('comment_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='user_comments_comment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id', name='user_comments_pkey')
    )
    # ### end Alembic commands ###
