"""empty message

Revision ID: 8b6e43221dad
Revises: 674d1ad643b6
Create Date: 2021-05-04 15:55:21.654679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b6e43221dad'
down_revision = '674d1ad643b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_posts',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('post_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.drop_table('userposts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userposts',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='userposts_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='userposts_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name='userposts_pkey')
    )
    op.drop_table('user_posts')
    # ### end Alembic commands ###
