"""empty message

Revision ID: d3ed8f6bfb77
Revises: 8b6e43221dad
Create Date: 2021-05-05 16:39:11.388869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ed8f6bfb77'
down_revision = '8b6e43221dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('avatarurl', sa.String(length=200), nullable=True))
    op.add_column('feeds', sa.Column('description', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'description')
    op.drop_column('feeds', 'avatarurl')
    # ### end Alembic commands ###
